
services:
  rustlog-proxy:
    image: ghcr.io/mrchuw/rustlog-proxy:master
    volumes:
      - ./.env:/.env
    ports:
      - "18080:18080"
    # environment:
      # - RECENT_URL=https://example.com/recent-messages/
      # - RUSTLOG_URL=https://example.com/
      # - RUSTLOG_API=mysecretkey
      # - LISTEN_ADDR=:8080   # opcional
